name: gg_changelog
description: gg_changelog offers various tools manipulate dart CHANGELOG.md files. Based on cider package.
version: 1.0.9
repository: https://github.com/inlavigo/gg_changelog.git

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  args: ^2.4.2
  cider: ^0.2.7
  gg_args: ^1.1.10
  gg_console_colors: ^2.1.0
  gg_log: ^1.0.1
  gg_process: ^1.1.2
  gg_status_printer: ^1.1.0
  mocktail: ^1.0.3
  path: ^1.8.0
  pub_semver: ^2.1.4

dev_dependencies:
  gg_capture_print: ^1.0.4
  gg_install_gg: ^1.0.2
  lints: ^3.0.0
  pana: ^0.22.2
  test: ^1.24.0

executables:
  gg_changelog:
